# We set the language to c because python isn't supported on the MacOS X nodes
# on Travis. However, the language ends up being irrelevant anyway, since we
# install Python ourselves using conda.
language: c

os:
    - linux

# Use Travis' container-based architecture
sudo: false

env:
    global:
        # The following versions are the 'default' for tests, unless
        # overidden underneath. They are defined here in order to save having
        # to repeat them for all configurations.
        - TOXENV='test'
        - TOXARGS='-v'
        - TOXPOSARGS=''

matrix:
    include:

        - language: python
          python: 3.6
          env: TOXENV=py36-test-pytest46

        - os: windows
          env: PYTHON_VERSION=3.6
               TOXENV=py36-test-pytest50

        - os: osx
          env: PYTHON_VERSION=3.7
               TOXENV=py37-test-pytest51

        - language: python
          python: 3.7
          env: TOXENV=py37-test-pytest52

        - os: windows
          env: PYTHON_VERSION=3.8
               TOXENV=py38-test-pytest53

        - os: osx
          env: PYTHON_VERSION=3.8
               TOXENV=py38-test-pytestdev

install:
    - if [[ $TRAVIS_OS_NAME == osx || $TRAVIS_OS_NAME == windows ]]; then
        git clone git://github.com/astropy/ci-helpers.git;
        source ci-helpers/travis/setup_conda.sh;
      fi

script:
    - pip install tox
    - tox $TOXARGS -- $TOXPOSARGS
